name = "MXs"
prefix = "gobmx"
author = "YonV"
template = "cba"
mainprefix = "z"
include = ["./include"]
folder_optionals = true
sig_version = 3

files = [
    "mod.cpp",
    "gobp2_256_g.paa",
    "gobp2_256.paa",
    "gobp2_512.paa",
    "gbbanner_booboo.paa"
    ]

exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"
key_name = "gobmx_{{version}}"
authority = "gobmx_{{version}}-"


check = [
    "!compile_scripts"
]

postbuild = [
    "!remove_compiled_scripts"
]

releasebuild = [
    "@zip @MXs_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"


[scripts.compile_scripts]
steps_windows = [
    "echo 'Compile Arma Scripts'",
    "ArmaScriptCompiler"
]

steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = false

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo 'remove Compiled Scripts'",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = true